// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArhtaQKYvFTSzZVAbaf27VtjtI7pWVgKM',
    appId: '1:935961367069:web:c93ad82cdf93b9d5c92cf4',
    messagingSenderId: '935961367069',
    projectId: 'notes-ee228',
    authDomain: 'notes-ee228.firebaseapp.com',
    storageBucket: 'notes-ee228.appspot.com',
    measurementId: 'G-7E7KLGDDJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPCyQ8tMARGEb_RUrkEtjFkXFI3YxAb7c',
    appId: '1:935961367069:android:2780aa2cfce623b9c92cf4',
    messagingSenderId: '935961367069',
    projectId: 'notes-ee228',
    storageBucket: 'notes-ee228.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4-C7cSzg5BtNb99Fl7Ei1RGG13dJ5y08',
    appId: '1:935961367069:ios:bddc3d567d9997ccc92cf4',
    messagingSenderId: '935961367069',
    projectId: 'notes-ee228',
    storageBucket: 'notes-ee228.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4-C7cSzg5BtNb99Fl7Ei1RGG13dJ5y08',
    appId: '1:935961367069:ios:35ea3870a0bb2159c92cf4',
    messagingSenderId: '935961367069',
    projectId: 'notes-ee228',
    storageBucket: 'notes-ee228.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
